- name: Add repository for PHP 8.2
  apt_repository:
    repo=ppa:ondrej/php
    update_cache=yes

- name: Install Php8.2 and its extenstions
  apt:
    name:
      - php8.2
      - libapache2-mod-php8.2
      - php8.2-common
      - php8.2-gmp
      - php8.2-curl
      - php8.2-soap
      - php8.2-bcmath
      - php8.2-intl
      - php8.2-mbstring
      - php8.2-xmlrpc
      - php8.2-mysql
      - php8.2-gd
      - php8.2-xml
      - php8.2-cli
      - php8.2-zip
      - php8.2-fpm
    state: latest
    update_cache: true

